name: Deploy Ftp Eportal web php
on: push
jobs:
  deploy:
  name: Deploy
  steps:
  - uses: actions/checkout@v1
  - name: git-ftp push
    uses: sebastianpopp/git-ftp-action@releases/v3
    with:
      url: "ftpx.forpsi.com"
      user: "kouzelnikrobin.cz"
      password: ${{secrets.FTP_PASSWORD}}